include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/generated_plugin_registrant.dart'

linter:
  rules:
    public_member_api_docs: false
    prefer_asserts_with_message: false
    flutter_style_todos: false
    diagnostic_describe_all_properties: false
    # Enable and fix these one by one
    cascade_invocations: false
    lines_longer_than_80_chars: false
