include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/generated_plugin_registrant.dart'

linter:
  rules:
    public_member_api_docs: false
    prefer_asserts_with_message: false
    flutter_style_todos: false
    # Enable and fix these one by one
    library_private_types_in_public_api: false
    cascade_invocations: false
    lines_longer_than_80_chars: false
    use_colored_box: false
